---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# DirtyFriday

<!-- badges: start -->

<!-- badges: end -->

Lo scopo di `DirtyFriday` è quello di collezionare e condividere il
materiale delle sessioni "DirtyFriday" che tengo il venerdì pomeriggio
per sperimentare, mostrare e condividere le mie idee su come poter
scrivere script e progetti R in modo pulito, leggibile, robusto,
condivisible, affidabile, facilmente collaborativo, e il tutto senza
eccessivi sforzi o strutture. Progetto per progetto, quanto basta per
ottenere le caratteristiche adeguate e utili per la dimensione dello
stesso.

Unisciti a me in questa serie di esperienze live (registrate e rese
disponibili su
[youtube](https://www.youtube.com/playlist?list=PLBf05gtbw86B-cVurq_rJbCUK8h5LVCMj))
in cui esploreremo insieme come trasformare script e progetti R in
codice pulito, riproducibile, robusto e facile da capire. Invece di
concentrarci su come risolvere i problemi specifici, ci concentreremo su
come creare o trasformare codice che sia ben predisposto per lo sviluppo
collaborativo. Ti mostrerò come utilizzare le migliori pratiche per il
refactoring, come organizzare il tuo codice e come documentarlo in modo
efficace. Non avrà molta importanza che tu sia un principiante o un
esperto di R, cercherò comunque di fornirti degli strumenti per creare
codice R di qualità superiore.

| Data       | Progetto                                    | Video                                                                                                                                  |
|--------------------|---------------------|-------------------------------|
| 2023-01-20 | [20230120](/20230120-tm/)[-tm](20230120-tm) | [refactor("TextMining", type = "script")](https://www.youtube.com/watch?v=Z_ZQn_wJPhU&list=PLBf05gtbw86B-cVurq_rJbCUK8h5LVCMj&index=1) |
| 2023-02-03 | [20230203-gtsummary](/20230203-gtsummary/)  | [refactor("gtsummary", type = "script")](https://www.youtube.com/watch?v=Cf1_bd6mjms)                                                  |
